services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error # opcional
      # Password: admin/deluge
    volumes:
      - ${DELUGE_CONFIG_PATH}:/config
      - ${DELUGE_DOWNLOADS_PATH}:/downloads
      - ${DELUGE_MOVIES_PATH}:/data/movies
      - ${DELUGE_SERIES_PATH}:/data/series
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 # opcional
    restart: unless-stopped
    network_mode: "bridge"

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    ports:
      - ${PROWLARR_PORT-9696}:9696
    restart: unless-stopped
    network_mode: "bridge"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${RADARR_MOVIES_PATH}:/data/movies
      - ${RADARR_DOWNLOADS_PATH}:/downloads
    ports:
      - ${RADARR_PORT-7878}:7878
    restart: unless-stopped
    network_mode: "bridge"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${SONARR_TV_PATH}:/tv
      - ${SONARR_DOWNLOADS_PATH}:/downloads
    ports:
      - ${SONARR_PORT-8989}:8989
    restart: unless-stopped
    network_mode: "bridge"

  plex:
    image: jaymoulin/plex:1.30.1.6562
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PLEX_MOVIES_PATH}:/data/movies
      - ${PLEX_TV_PATH}:/data/tvshows
    ports:
      - ${PLEX_PORT-32400}:32400
    restart: unless-stopped
    network_mode: "bridge"

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    volumes:
      - ${NZBGET_CONFIG_PATH}:/config
      - ${NZBGET_DOWNLOADS_PATH}:/downloads
    ports:
      - ${NZBGET_PORT-6789}:6789
    restart: unless-stopped
    network_mode: "bridge"